### ISSUE TITLE
有什么需要注意的吗

### ISSUE THREAD

**Issue by nealma** [alibaba/TProfiler#32]
java -cp tprofiler.jar com.taobao.profile.client.TProfilerClient 127.0.0.1 4096 status

java.net.ConnectException: 拒绝连接
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at java.net.Socket.<init>(Socket.java:425)
    at java.net.Socket.<init>(Socket.java:208)
    at com.taobao.profile.client.TProfilerClient.getStatus(TProfilerClient.java:112)
    at com.taobao.profile.client.TProfilerClient.status(TProfilerClient.java:57)
    at com.taobao.profile.client.TProfilerClient.main(TProfilerClient.java:173)

**Comment by jlusdy** [comment]
端口不对吗
