### ISSUE TITLE
tprofiler-master版本 启动报错数组下标越界

### ISSUE THREAD

**Issue by huzhiwei870804** [alibaba/TProfiler#53]
java.lang.ArrayIndexOutOfBoundsException: 52264
        at org.objectweb.asm.ClassReader.readClass(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.taobao.profile.instrument.ProfTransformer.transform(ProfTransformer.java:55)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)

**Comment by mccxj** [comment]
看上去tprofiler不支持JDK 8 Lambdas，不过我会修复这个问题。

**Comment by mccxj** [comment]
@huzhiwei870804 我已经修改了，提交记录为 https://github.com/mccxj/TProfiler/commit/36e45e0563c56c8060ddd72ad2b8208169f3b4d3

**Comment by future1314** [comment]
ok
